//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WaterBillingSystemUI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WaterBillingSystemEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WaterBillingSystemEntities object using the connection string found in the 'WaterBillingSystemEntities' section of the application configuration file.
        /// </summary>
        public WaterBillingSystemEntities() : base("name=WaterBillingSystemEntities", "WaterBillingSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WaterBillingSystemEntities object.
        /// </summary>
        public WaterBillingSystemEntities(string connectionString) : base(connectionString, "WaterBillingSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WaterBillingSystemEntities object.
        /// </summary>
        public WaterBillingSystemEntities(EntityConnection connection) : base(connection, "WaterBillingSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Angilan> tbl_Angilan
        {
            get
            {
                if ((_tbl_Angilan == null))
                {
                    _tbl_Angilan = base.CreateObjectSet<tbl_Angilan>("tbl_Angilan");
                }
                return _tbl_Angilan;
            }
        }
        private ObjectSet<tbl_Angilan> _tbl_Angilan;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Angilan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Angilan(tbl_Angilan tbl_Angilan)
        {
            base.AddObject("tbl_Angilan", tbl_Angilan);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WaterBillingSystemModel", Name="tbl_Angilan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Angilan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Angilan object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tbl_Angilan Createtbl_Angilan(global::System.Int32 id)
        {
            tbl_Angilan tbl_Angilan = new tbl_Angilan();
            tbl_Angilan.ID = id;
            return tbl_Angilan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Customer_Code
        {
            get
            {
                return _Customer_Code;
            }
            set
            {
                OnCustomer_CodeChanging(value);
                ReportPropertyChanging("Customer_Code");
                _Customer_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Customer_Code");
                OnCustomer_CodeChanged();
            }
        }
        private global::System.String _Customer_Code;
        partial void OnCustomer_CodeChanging(global::System.String value);
        partial void OnCustomer_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Meter_Number
        {
            get
            {
                return _Meter_Number;
            }
            set
            {
                OnMeter_NumberChanging(value);
                ReportPropertyChanging("Meter_Number");
                _Meter_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Meter_Number");
                OnMeter_NumberChanged();
            }
        }
        private global::System.String _Meter_Number;
        partial void OnMeter_NumberChanging(global::System.String value);
        partial void OnMeter_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Current_Reading
        {
            get
            {
                return _Current_Reading;
            }
            set
            {
                OnCurrent_ReadingChanging(value);
                ReportPropertyChanging("Current_Reading");
                _Current_Reading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Current_Reading");
                OnCurrent_ReadingChanged();
            }
        }
        private Nullable<global::System.Int32> _Current_Reading;
        partial void OnCurrent_ReadingChanging(Nullable<global::System.Int32> value);
        partial void OnCurrent_ReadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Previous_Reading
        {
            get
            {
                return _Previous_Reading;
            }
            set
            {
                OnPrevious_ReadingChanging(value);
                ReportPropertyChanging("Previous_Reading");
                _Previous_Reading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Previous_Reading");
                OnPrevious_ReadingChanged();
            }
        }
        private Nullable<global::System.Int32> _Previous_Reading;
        partial void OnPrevious_ReadingChanging(Nullable<global::System.Int32> value);
        partial void OnPrevious_ReadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Consumed
        {
            get
            {
                return _Consumed;
            }
            set
            {
                OnConsumedChanging(value);
                ReportPropertyChanging("Consumed");
                _Consumed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Consumed");
                OnConsumedChanged();
            }
        }
        private Nullable<global::System.Decimal> _Consumed;
        partial void OnConsumedChanging(Nullable<global::System.Decimal> value);
        partial void OnConsumedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Less_Cubic_Meter
        {
            get
            {
                return _Less_Cubic_Meter;
            }
            set
            {
                OnLess_Cubic_MeterChanging(value);
                ReportPropertyChanging("Less_Cubic_Meter");
                _Less_Cubic_Meter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Less_Cubic_Meter");
                OnLess_Cubic_MeterChanged();
            }
        }
        private Nullable<global::System.Int32> _Less_Cubic_Meter;
        partial void OnLess_Cubic_MeterChanging(Nullable<global::System.Int32> value);
        partial void OnLess_Cubic_MeterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total_Cubic_Meter
        {
            get
            {
                return _Total_Cubic_Meter;
            }
            set
            {
                OnTotal_Cubic_MeterChanging(value);
                ReportPropertyChanging("Total_Cubic_Meter");
                _Total_Cubic_Meter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Cubic_Meter");
                OnTotal_Cubic_MeterChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total_Cubic_Meter;
        partial void OnTotal_Cubic_MeterChanging(Nullable<global::System.Decimal> value);
        partial void OnTotal_Cubic_MeterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount_Per_Cubic_Meter
        {
            get
            {
                return _Amount_Per_Cubic_Meter;
            }
            set
            {
                OnAmount_Per_Cubic_MeterChanging(value);
                ReportPropertyChanging("Amount_Per_Cubic_Meter");
                _Amount_Per_Cubic_Meter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount_Per_Cubic_Meter");
                OnAmount_Per_Cubic_MeterChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount_Per_Cubic_Meter;
        partial void OnAmount_Per_Cubic_MeterChanging(Nullable<global::System.Decimal> value);
        partial void OnAmount_Per_Cubic_MeterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Current_Bill
        {
            get
            {
                return _Current_Bill;
            }
            set
            {
                OnCurrent_BillChanging(value);
                ReportPropertyChanging("Current_Bill");
                _Current_Bill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Current_Bill");
                OnCurrent_BillChanged();
            }
        }
        private Nullable<global::System.Decimal> _Current_Bill;
        partial void OnCurrent_BillChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrent_BillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Previous_Balance
        {
            get
            {
                return _Previous_Balance;
            }
            set
            {
                OnPrevious_BalanceChanging(value);
                ReportPropertyChanging("Previous_Balance");
                _Previous_Balance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Previous_Balance");
                OnPrevious_BalanceChanged();
            }
        }
        private global::System.String _Previous_Balance;
        partial void OnPrevious_BalanceChanging(global::System.String value);
        partial void OnPrevious_BalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Amount_Paid
        {
            get
            {
                return _Amount_Paid;
            }
            set
            {
                OnAmount_PaidChanging(value);
                ReportPropertyChanging("Amount_Paid");
                _Amount_Paid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Amount_Paid");
                OnAmount_PaidChanged();
            }
        }
        private global::System.String _Amount_Paid;
        partial void OnAmount_PaidChanging(global::System.String value);
        partial void OnAmount_PaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date_Paid
        {
            get
            {
                return _Date_Paid;
            }
            set
            {
                OnDate_PaidChanging(value);
                ReportPropertyChanging("Date_Paid");
                _Date_Paid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date_Paid");
                OnDate_PaidChanged();
            }
        }
        private global::System.String _Date_Paid;
        partial void OnDate_PaidChanging(global::System.String value);
        partial void OnDate_PaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OR_No
        {
            get
            {
                return _OR_No;
            }
            set
            {
                OnOR_NoChanging(value);
                ReportPropertyChanging("OR_No");
                _OR_No = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OR_No");
                OnOR_NoChanged();
            }
        }
        private global::System.String _OR_No;
        partial void OnOR_NoChanging(global::System.String value);
        partial void OnOR_NoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                OnBalanceChanging(value);
                ReportPropertyChanging("Balance");
                _Balance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Balance");
                OnBalanceChanged();
            }
        }
        private global::System.String _Balance;
        partial void OnBalanceChanging(global::System.String value);
        partial void OnBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Added_Date
        {
            get
            {
                return _Added_Date;
            }
            set
            {
                OnAdded_DateChanging(value);
                ReportPropertyChanging("Added_Date");
                _Added_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Added_Date");
                OnAdded_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Added_Date;
        partial void OnAdded_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnAdded_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Other_Information
        {
            get
            {
                return _Other_Information;
            }
            set
            {
                OnOther_InformationChanging(value);
                ReportPropertyChanging("Other_Information");
                _Other_Information = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Other_Information");
                OnOther_InformationChanged();
            }
        }
        private global::System.String _Other_Information;
        partial void OnOther_InformationChanging(global::System.String value);
        partial void OnOther_InformationChanged();

        #endregion

    
    }

    #endregion

    
}
